# Generated by Django 6.1 — email verification support.

from django.db import migrations, models


def mark_existing_users_verified(apps, schema_editor):
    """Уже существующие пользователи считаются подтверждёнными (иначе они бы потеряли вход)."""
    User = apps.get_model('users', 'User')
    User.objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email подтверждён'),
        ),
        migrations.RunPython(mark_existing_users_verified, migrations.RunPython.noop),
    ]