# Generated by Django 6.1 on 2026-09-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название таблицы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cells', models.JSONField(blank=True, default=list, verbose_name='Ячейки')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Таблица цен',
                'verbose_name_plural': 'Таблицы цен',
                'ordering': ['order', 'id'],
            },
        ),
    ]
