# Generated by Django 6.1 on 2026-09-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sand', 'Пескоструй'), ('powder', 'Порошковая покраска'), ('weld', 'Сварка')], max_length=10, verbose_name='Категория')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_from', models.PositiveIntegerField(verbose_name='Цена от, ₽')),
                ('price_unit', models.CharField(default='за м²', max_length=50, verbose_name='Единица измерения')),
                ('icon', models.CharField(default='⚙', max_length=10, verbose_name='Иконка (emoji)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('order', 'id'),
            },
        ),
    ]
