# Generated by Django 6.1 on 2026-09-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutimage',
            name='pos_x',
            field=models.CharField(choices=[('left', 'Слева'), ('center', 'По центру'), ('right', 'Справа')], default='center', max_length=10, verbose_name='Центрование по горизонтали'),
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='pos_y',
            field=models.CharField(choices=[('top', 'Сверху'), ('center', 'По центру'), ('bottom', 'Снизу')], default='center', max_length=10, verbose_name='Центрование по вертикали'),
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='scale',
            field=models.PositiveIntegerField(default=100, verbose_name='Размер, %'),
        ),
    ]
