# Generated by Django 6.1 on 2026-09-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                (
                    'image_before',
                    models.ImageField(blank=True, upload_to='portfolio/before/%Y/%m/', verbose_name='До'),
                ),
                ('image_after', models.ImageField(upload_to='portfolio/after/%Y/%m/', verbose_name='После')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'service',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='portfolio',
                        to='services.service',
                        verbose_name='Услуга',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ('-created_at',),
            },
        ),
    ]
