# Generated by Django 6.1 on 2026-09-17 09:40

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_images(apps, schema_editor):
    """Переносит одиночные фото image_before/image_after в модель PortfolioImage."""
    PortfolioItem = apps.get_model('portfolio', 'PortfolioItem')
    PortfolioImage = apps.get_model('portfolio', 'PortfolioImage')
    for item in PortfolioItem.objects.all().iterator():
        if item.image_before:
            PortfolioImage.objects.create(
                item_id=item.id,
                kind='before',
                image=item.image_before,
                order=0,
            )
        if item.image_after:
            PortfolioImage.objects.create(
                item_id=item.id,
                kind='after',
                image=item.image_after,
                order=0,
            )


def restore_legacy_images(apps, schema_editor):
    """Восстанавливает одиночные фото из первой записи каждого типа (для отката)."""
    PortfolioItem = apps.get_model('portfolio', 'PortfolioItem')
    PortfolioImage = apps.get_model('portfolio', 'PortfolioImage')
    for item in PortfolioItem.objects.all().iterator():
        first_before = PortfolioImage.objects.filter(item_id=item.id, kind='before').first()
        if first_before:
            item.image_before = first_before.image
        first_after = PortfolioImage.objects.filter(item_id=item.id, kind='after').first()
        if first_after:
            item.image_after = first_after.image
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'kind',
                    models.CharField(
                        choices=[('before', 'До'), ('after', 'После')], max_length=10, verbose_name='Тип фото'
                    ),
                ),
                ('image', models.ImageField(upload_to='portfolio/%Y/%m/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='portfolio.portfolioitem',
                        verbose_name='Работа',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Фото работы',
                'verbose_name_plural': 'Фото работ',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.RunPython(copy_legacy_images, restore_legacy_images),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='image_after',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='image_before',
        ),
    ]
