# Generated by Django 6.1 on 2026-10-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolioitem_image_after_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ('created_at',), 'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='thumb',
            field=models.ImageField(
                blank=True,
                help_text='Маленькая копия для ускорения загрузки карточек',
                null=True,
                upload_to='portfolio/thumbs/%Y/%m/',
                verbose_name='Эскиз',
            ),
        ),
    ]
